version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: your_username
      DB_PASSWORD: your_password
      DB_NAME: your_database
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
